# Config Coturn basique
realm=kroom.io
fingerprint
listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
verbose
user=kroom:kroom_pass
lt-cred-mech
stale-nonce=600
no-stdout-log
log-file=/var/tmp/turn.log
mobility
no-cli
no-tlsv1
no-tlsv11
# Requis pour Docker
external-ip=0.0.0.0
